[package]
name = "bubblechamber-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
arraydeque = "0.4"
nannou = "0.18"
ndarray = "0.15"
rand = "0.8"
rand_distr = "0.4"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
