[chamber]
magnetic_field_strength = 5.0
friction = 0.05

[particles]
at_start = 5
avg_per_s = 3.0
mass_mean = 3.0
mass_stddev = 0.6
velocity_mean = 3000.0
max_charge = 2
lifetime_exp_lambda = 2.0

[graphics]
wipe_background = true
draw_neutral = false
style = "Original"
