logging:
    version: 1
    loggers:
        genart:
            level: INFO
            handlers: [console]
    handlers:
        console:
            class: logging.StreamHandler
            level: INFO
            formatter: basic
            stream: ext://sys.stdout
    formatters:
        basic:
            format: '%(asctime)s %(name)s [%(levelname)s] %(message)s'
